# AUTO-GENERATED by scripts/sync_jurisdictions.py — do not edit manually.
# Source: terms-analysis/src/backend/app/schemas.py Jurisdiction Literal
# Run `python scripts/sync_jurisdictions.py` to regenerate.
from __future__ import annotations

JURISDICTION_CODES: frozenset[str] = frozenset({
    "APP",
    "APPI",
    "CA-QC",
    "COE-108",
    "COE-AI-225",
    "DPDP",
    "EU-AI-ACT",
    "GDPR",
    "ICCPR-17",
    "LGPD",
    "NDPR",
    "OECD-AI",
    "PDPA-KE",
    "PDPA-TH",
    "PIPA",
    "PIPEDA",
    "POPIA",
    "UK-GDPR",
    "UNESCO-AI",
    "US-CA",
    "US-CO",
    "US-CT",
    "US-FED",
    "US-IL",
    "US-MN",
    "US-NJ",
    "US-NY",
    "US-OR",
    "US-TX",
    "US-VA",
})
