#!/usr/bin/env python3
"""sync_jurisdictions.py — generate jurisdictions.py from terms-analysis schemas.py.

Reads the Jurisdiction Literal from terms-analysis::schemas.py via AST parsing
and writes src/legal_corpus_ingester/jurisdictions.py with a frozenset.

Run: python scripts/sync_jurisdictions.py
Idempotent: running twice produces identical output.

The terms-analysis checkout is TERMS_ANALYSIS_ROOT when that is set and not
empty (CI checks it out into the workspace), else the directory named
terms-analysis beside this repo.
"""
from __future__ import annotations
import ast
import os
import sys
from pathlib import Path

ROOT_ENV = "TERMS_ANALYSIS_ROOT"
DEFAULT_TERMS_ANALYSIS_ROOT = Path(__file__).resolve().parent.parent.parent / "terms-analysis"
SCHEMAS_IN_ROOT = Path("src") / "backend" / "app" / "schemas.py"
OUT_FILE = Path(__file__).parent.parent / "src" / "legal_corpus_ingester" / "jurisdictions.py"

HEADER = '''\
# AUTO-GENERATED by scripts/sync_jurisdictions.py — do not edit manually.
# Source: terms-analysis/src/backend/app/schemas.py Jurisdiction Literal
# Run `python scripts/sync_jurisdictions.py` to regenerate.
from __future__ import annotations

JURISDICTION_CODES: frozenset[str] = frozenset({{
{entries}
}})
'''


def _extract_literal_strings(slice_node: ast.expr) -> list[str]:
    """Extract string constants from a Literal slice (Tuple or single Constant)."""
    codes: list[str] = []
    if isinstance(slice_node, ast.Tuple):
        for elt in slice_node.elts:
            if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                codes.append(elt.value)
    elif isinstance(slice_node, ast.Constant) and isinstance(slice_node.value, str):
        codes.append(slice_node.value)
    return codes


def extract_jurisdiction_codes(schemas_path: Path) -> list[str]:
    """Parse schemas.py AST to extract Jurisdiction Literal string arguments.

    Handles both:
    - ``Jurisdiction = Literal[...]``  (ast.Assign)
    - ``Jurisdiction: TypeAlias = Literal[...]``  (ast.AnnAssign)
    """
    source = schemas_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(schemas_path))
    for node in ast.walk(tree):
        # Handle: Jurisdiction = Literal[...]
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "Jurisdiction":
                    if isinstance(node.value, ast.Subscript):
                        codes = _extract_literal_strings(node.value.slice)
                        if codes:
                            return codes
        # Handle: Jurisdiction: TypeAlias = Literal[...]
        if isinstance(node, ast.AnnAssign):
            target = node.target
            if isinstance(target, ast.Name) and target.id == "Jurisdiction":
                ann = node.annotation
                if isinstance(ann, ast.Subscript):
                    codes = _extract_literal_strings(ann.slice)
                    if codes:
                        return codes
    raise ValueError(f"Could not find 'Jurisdiction' Literal assignment in {schemas_path}")


def terms_analysis_schemas() -> Path:
    """terms-analysis's schemas.py, under TERMS_ANALYSIS_ROOT or the default."""
    root = os.environ.get(ROOT_ENV, "")
    return (Path(root) if root else DEFAULT_TERMS_ANALYSIS_ROOT) / SCHEMAS_IN_ROOT


def main() -> None:
    schemas = terms_analysis_schemas()
    if not schemas.is_file():
        print(
            f"ERROR: terms-analysis schemas not found at {schemas} "
            f"(set {ROOT_ENV} to the terms-analysis checkout)",
            file=sys.stderr,
        )
        sys.exit(1)

    codes = sorted(extract_jurisdiction_codes(schemas))
    entries = "\n".join(f'    "{code}",' for code in codes)
    content = HEADER.format(entries=entries)
    OUT_FILE.write_text(content, encoding="utf-8")
    print(f"Written {len(codes)} jurisdiction codes to {OUT_FILE}")


if __name__ == "__main__":
    main()
